// A simple “database” of coffee recipes const coffeeRecipes = [ { name: "Classic Espresso", ideal: { mood: ["energetic", "focused"], taste: ["bold", "balanced"], timeOfDay: ["morning", "afternoon"], decaf: false, extraShot: false }, description: "A strong and bold espresso shot that jumpstarts your day.", ingredients: ["Fresh coffee beans - 18g", "Water - 30ml"], equipment: ["Gaggia Classic GT", "Tamper", "Measuring Scoop"], steps: [ "Step 1: Preheat the filter holder by running hot water.", "Step 2: Grind coffee beans to a fine espresso grind.", "Step 3: Tamp the coffee into the portafilter.", "Step 4: Brew until you reach ~30ml of espresso." ], serving: "Serve as-is or pair with a sweet pastry." }, { name: "Sweet Latte", ideal: { mood: ["relaxed"], taste: ["sweet"], timeOfDay: ["morning", "afternoon"], decaf: false, extraShot: false }, description: "A mellow, sweet latte perfect for a relaxed mood. Topped with silky milk foam.", ingredients: [ "Fresh coffee beans - 18g", "Water - 30ml", "Cold milk - 100ml" ], equipment: ["Gaggia Classic GT", "Milk jug", "Tamper"], steps: [ "Step 1: Brew a standard espresso shot.", "Step 2: Froth cold milk using the steam wand.", "Step 3: Gently pour the frothed milk over the espresso." ], serving: "Pair with a light snack or enjoy solo." }, { name: "Decaf Cappuccino", ideal: { mood: ["relaxed", "focused"], taste: ["balanced"], timeOfDay: ["evening"], decaf: true, extraShot: false }, description: "A balanced cappuccino made with decaffeinated beans for late-day enjoyment.", ingredients: [ "Decaf coffee beans - 18g", "Water - 30ml", "Cold milk - 100ml" ], equipment: ["Gaggia Classic GT", "Milk jug", "Tamper"], steps: [ "Step 1: Brew a decaf espresso shot.", "Step 2: Froth milk with the steam wand until velvety.", "Step 3: Combine espresso and frothed milk in your cup." ], serving: "Sprinkle cocoa on top for an extra treat." }, { name: "Extra Shot Mocha", ideal: { mood: ["energetic", "focused"], taste: ["sweet", "bold"], timeOfDay: ["morning", "afternoon"], decaf: false, extraShot: true }, description: "A rich mocha with an extra shot for that intense caffeine kick.", ingredients: [ "Coffee beans - 18g + 9g extra shot", "Water - 45ml total", "Chocolate syrup - 10ml", "Cold milk - 100ml" ], equipment: ["Gaggia Classic GT", "Milk jug", "Tamper", "Chocolate syrup"], steps: [ "Step 1: Brew a double espresso (two shots).", "Step 2: Mix chocolate syrup into the espresso.", "Step 3: Froth milk and pour it over the chocolate-espresso base." ], serving: "Top with whipped cream and chocolate shavings." } ];

/**

Form Submission on index.html */ window.addEventListener("DOMContentLoaded", function () { const coffeeForm = document.getElementById("coffeeForm"); if (coffeeForm) { coffeeForm.addEventListener("submit", (e) => { e.preventDefault();

// Gather user inputs const mood = document.getElementById("mood").value; const taste = document.getElementById("taste").value; const timeOfDay = document.getElementById("timeOfDay").value; const decaf = document.getElementById("decaf").checked; const extraShot = document.getElementById("extraShot").checked;

// Store in localStorage const userPreferences = { mood, taste, timeOfDay, decaf, extraShot }; localStorage.setItem("userPreferences", JSON.stringify(userPreferences));

// Redirect to recommendation page window.location.href = "recommendation.html"; }); }

/**

2) Recommendation Logic on recommendation.html */ if (window.location.pathname.includes("recommendation.html")) { const storedPrefs = localStorage.getItem("userPreferences"); if (!storedPrefs) return; // If no prefs found, do nothing
